"""add use_custom_llm to agents

Revision ID: 040647be7908
Revises: 4f42c8f91820
Create Date: 2026-07-30 14:40:29.534859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040647be7908'
down_revision: Union[str, None] = '4f42c8f91820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: the "agents" table already has rows (e.g. the
    # existing "Ali" agent) — a NOT NULL column with no default fails against them.
    op.add_column(
        'agents',
        sa.Column('use_custom_llm', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'use_custom_llm')
    # ### end Alembic commands ###
