"""add batch runs

Revision ID: 1d467d365093
Revises: c3d9f1a25b40
Create Date: 2026-09-02 10:30:10.817773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d467d365093'
down_revision: Union[str, None] = 'c3d9f1a25b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_runs',
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('external_agent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dynamic_variables', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_runs_status'), 'batch_runs', ['status'], unique=False)
    op.create_index(op.f('ix_batch_runs_tenant_id'), 'batch_runs', ['tenant_id'], unique=False)
    op.create_table('batch_run_items',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('prospect_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('skip_reason', sa.String(length=255), nullable=True),
    sa.Column('dialed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['batch_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_run_items_run_id'), 'batch_run_items', ['run_id'], unique=False)
    op.create_index(op.f('ix_batch_run_items_status'), 'batch_run_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_run_items_status'), table_name='batch_run_items')
    op.drop_index(op.f('ix_batch_run_items_run_id'), table_name='batch_run_items')
    op.drop_table('batch_run_items')
    op.drop_index(op.f('ix_batch_runs_tenant_id'), table_name='batch_runs')
    op.drop_index(op.f('ix_batch_runs_status'), table_name='batch_runs')
    op.drop_table('batch_runs')
    # ### end Alembic commands ###
