"""add llm_model to agents

Revision ID: 79342e6251f7
Revises: 040647be7908
Create Date: 2026-08-03 14:05:35.595631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79342e6251f7'
down_revision: Union[str, None] = '040647be7908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: the "agents" table already has rows — a NOT NULL
    # column with no default fails against them (same reasoning as
    # 040647be7908_add_use_custom_llm_to_agents.py). "" means "use
    # settings.default_llm_model" (see backend/services/llm_service.py).
    op.add_column(
        'agents',
        sa.Column('llm_model', sa.String(length=100), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'llm_model')
    # ### end Alembic commands ###
